config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :feed_categories
  resources :feeds, only: [:index, :new, :create, :show, :update] do
    member do
      # recognizes get `/feeds/:id/settings` and routes to feeds#settings, w feed.id passed in params[:id] & settings_feed_path helper created
      get 'settings'
      patch 'settings', to: 'feeds#update_settings'
    end
    resources :entries, only: [:show]
    get '/entries', to: 'entries#refresh'
  end
  resources :entries, only: [:index] do
    member do
      get 'settings'
      patch 'settings', to: 'entries#update_settings'
    end
  end
  resources :users
  resources :feed_subscriptions

  get '/feeds/:id/refresh', to: 'feeds#refresh', as: 'refresh_feed'

  #Session Routes
  root 'application#home'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  get '/analytics', to: 'analytics#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :feed_subscriptions
  has_many :users, through: :feed_subscriptions
  has_many :feed_to_category_helpers
  has_many :feed_categories, through: :feed_to_category_helpers
  has_many :entries
  has_many :tags, through: :entries

  validates :feed_url, {presence: true, uniqueness: true}

  def self.search(search_term)

    @feed = add_scheme_to_search_url(search_term)

    if @feed.nil?
      feed_url = find_feed_from_url(search_term)

      if !feed_url.nil?
        feed = fetch_and_parse_feed(feed_url)

        @feed = Feed.new(
          url: feed.url,
          feed_url: feed_url,
          description: feed.description,
          title: feed.title
          )
        end
    else
      @feed
    end
  end

  def self.add_scheme_to_search_url(search_term)
    if search_term
      http = Feed.find_by(url: "http://#{search_term}")
      https = Feed.find_by(url: "https://#{search_term}")

      if http
        @feed = http
      elsif https
        @feed = https
      end
    end
  end

  def self.find_feed_from_url(url)
    Feedbag.find(url).first if url
  end

  def self.fetch_and_parse_feed(feed)
    Feedjira::Feed.fetch_and_parse(feed)
  end

  def refresh_feed
    new_entries = Feed.fetch_and_parse_feed(self.feed_url)

    new_entries.entries.each do |entry|
      if !!Entry.where(url: entry.url)
        Entry.create(feed: self,
          title: entry.title,
          url: entry.url,
          author: entry.author,
          published_datetime: entry.published,
          summary: entry.summary,
          content: entry.content
        )
      end
    end
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :update, :refresh, :settings, :update_settings]

  def index
    if !@current_user
      redirect_to login_path
    else
      @feeds = @current_user.feeds
    end
  end

  def show
    @entries = @feed.entries.order(published_datetime: :desc)
  end

  def new
    @feed = Feed.search(params[:search])
  end

  def create
    @feed = Feed.find_or_create_by(feed_params)
    @new_feed = FeedSubscription.find_or_create_by(user: @current_user, feed: @feed)

    feed_entries = Entry.write_new_entries(Feed.fetch_and_parse_feed(@feed.feed_url))

    redirect_to feed_path(@feed)
  end

  def update
    @new_feed = FeedSubscription.find_or_create_by(user: @current_user, feed: @feed)

    redirect_to feed_path(@feed)
  end

  def refresh
    @feed.refresh_feed

    redirect_to feed_path(@feed)
  end

  def settings
  end

  def update_settings
    @current_user.update_or_create_feed_cats(feed_params)
    redirect_to feed_path(@feed)
  end

  private

  def set_feed
    @feed = Feed.find(params[:id])
  end

  def feed_params
    params.require(:feed).permit(
      :title,
      :url,
      :description,
      :search,
      :feed_url,
      :id,
      feed_category_ids: [],
      feed_categories: [:title]
    )
  end

end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/index.html.erb
<div class="header">
  <%= button_to "Home", root_path, :method => "get" %>

  <h1>All Feeds</h1>
</div>

<div class="sub_header">
  <h3><%= link_to "Add Content", new_feed_path %></h3>
</div>

<ul>
  <% @feeds.each do |feed| %>
    <li><%= link_to feed.title, feed_path(feed) %></li>
    <li><%= feed.description %></li>
    
  <% end %>
</ul>

<div class="footer">
  <%= form_tag logout_path do %>
    <%= submit_tag "logout" %>
  <% end %>
</div>

app/views/feeds/new.html.erb
<div class="header">
  <%= button_to "Home", feeds_path, :method => "get" %>

  <h1>Susbcribe to a Feed</h1>
</div>

<div class="sub_header">
  <%= form_tag(new_feed_path, method: :get) do %>
      <%= label_tag(:search, "Search by URL") %>
      <%= text_field_tag(:search, params[:search]) %>
      <%= submit_tag ("Search") %>
  <% end %>

  <h3>Results</h3>

  <% if @feed %>
    <%= form_for @feed do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :url %>
      <%= f.hidden_field :description %>
      <%= f.hidden_field :feed_url %>
      <%= f.label @feed.title %>

      <br><%= f.submit "Subscribe to Feed" if @feed %>
    <% end %>
  <% end %>
</div>

app/views/feeds/settings.html.erb
<div class="header">
  <h3>Editing <%= @feed.title %></h3>
</div>

 <%= render 'shared/category_form' %>

app/views/feeds/show.html.erb
<div class="header">
  <%= button_to "Home", root_path, :method => "get" %>
  <h1><%= @feed.title %></h1>
</div>

<div class="sub_header">
  <%= link_to "Refresh Feed", refresh_feed_path(@feed) %> // <%= link_to "Feed Settings", settings_feed_path(@feed) %>

  <br><% @feed.feed_categories.each do |cat| %>
  / <%= link_to cat.title, feed_category_path(cat) %> /
  <% end %>
</div>


<ul>
  <% @entries.each do |entry| %>
    <li>
      <%= link_to entry.title, feed_entry_path(entry.feed, entry) %><br>
      <%= "#{entry.author} - #{entry.published_datetime.strftime("%-d %b %Y")}" %>
    </li>
  <% end %>
</ul>