config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :feed_categories
  resources :feeds, only: [:index, :new, :create, :show, :update] do
    member do
      # recognizes get `/feeds/:id/settings` and routes to feeds#settings, w feed.id passed in params[:id] & settings_feed_path helper created
      get 'settings'
      patch 'settings', to: 'feeds#update_settings'
    end
    resources :entries, only: [:show]
    get '/entries', to: 'entries#refresh'
  end
  resources :entries, only: [:index] do
    member do
      get 'settings'
      patch 'settings', to: 'entries#update_settings'
    end
  end
  resources :users
  resources :feed_subscriptions

  get '/feeds/:id/refresh', to: 'feeds#refresh', as: 'refresh_feed'

  #Session Routes
  root 'application#home'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  get '/analytics', to: 'analytics#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :feed
  has_many :entry_tags
  has_many :tags, through: :entry_tags

  validates :url, { presence: true, uniqueness: true }

  def self.write_new_entries(parsed_feed)
    feed = Feed.find_by(url: parsed_feed.url)

    parsed_feed.entries.each do |entry|
      Entry.create(
        feed: feed,
        title: entry.title,
        url: entry.url,
        author: entry.author,
        published_datetime: entry.published,
        summary: entry.summary,
        content: entry.content
      )
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :settings, :update_settings]

  def index
    @entries = @current_user.entries.order(published_datetime: :desc)
  end

  def show

  end

  def refresh
    # @current_user.feeds.each { |feed| feed.refresh_feed }
    #
    # redirect_to entries_path
  end

  def settings
  end

  def update_settings
    # binding.pry
    @current_user.update_or_create_tags(entry_params)
    redirect_to feed_entry_path(@entry)
  end

  private

  def set_entry
    @entry = Entry.find(params[:id])
  end

  def entry_params
    params.require(:entry).permit(:id, tag_ids: [], tags: [:name] )
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/index.html.erb
<div class="header">
  <%= button_to "Home", root_path, :method => "get" %>

  <h1>All Entries</h1>
</div>

<ul>
  <% @entries.each do |entry| %>
    <li>
      <%= link_to entry.title, feed_entry_path(entry.feed, entry) %><br>
      <%= link_to  entry.feed.title, feed_path(entry.feed) %> <%= "by #{entry.author} / #{entry.published_datetime.strftime("%-d %b %Y")}" %>
    </li>
  <% end %>
</ul>

app/views/entries/settings.html.erb
<div class="header">
  <h3>Add Tags to <%= @entry.title %></h3>
</div>

<div class="sub_header">
  <ul>
  <%= form_for @entry, url: settings_entry_path(@entry) do |f| %>
    <li><%= f.hidden_field :id %></li>

    <label><%= f.label :tags, "Tags" %></label>
    <li><%= f.collection_check_boxes :tag_ids, @current_user.tags, :id, :name%></li>

    <%= f.fields_for :tags, @current_user.tags.build do |cat| %>
      <li><%= cat.label :name, 'New Tag' %></li>
      <li><%= cat.text_field :name %></li>
    <% end %>
  </ul>
    <br><%= f.submit value: 'Save' %>
  <% end %>
</div>

app/views/entries/show.html.erb
<div class="header">
  <%= button_to "Home", feeds_path, :method => "get" %>
</div>

<div class="sub_header">
  <h1><%= link_to @entry.title, @entry.url %></h1>
  <%= link_to  @entry.feed.title, feed_path(@entry.feed) %> <%= "by #{@entry.author} / #{@entry.published_datetime.strftime("%-d %b %Y")} // read // hide" %>

  <% @entry.tags.each do |tag| %>
  / <%= link_to tag.name, tag_path(tag) %> /
  <% end %>

  <%= link_to "Add Tags", settings_entry_path(@entry) %>
</div>

<div class="entries">
  <%= sanitize @entry.summary %>  
</div>

<div class="footer">
  <%= button_to "Previous", feed_entry_path(@entry.feed, @entry.id - 1), method: :get %>
  <%= button_to "Next", feed_entry_path(@entry.feed, @entry.id + 1), method: :get %>
</div>