config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :feed_categories
  resources :feeds, only: [:index, :new, :create, :show, :update] do
    member do
      # recognizes get `/feeds/:id/settings` and routes to feeds#settings, w feed.id passed in params[:id] & settings_feed_path helper created
      get 'settings'
      patch 'settings', to: 'feeds#update_settings'
    end
    resources :entries, only: [:show]
    get '/entries', to: 'entries#refresh'
  end
  resources :entries, only: [:index] do
    member do
      get 'settings'
      patch 'settings', to: 'entries#update_settings'
    end
  end
  resources :users
  resources :feed_subscriptions

  get '/feeds/:id/refresh', to: 'feeds#refresh', as: 'refresh_feed'

  #Session Routes
  root 'application#home'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  get '/analytics', to: 'analytics#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user
  has_many :entry_tags
  has_many :entries, through: :entry_tags

  validates :name, { presence: true, uniqueness: true }
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show]

  def index
    @tags = Tag.all
  end

  def show

  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.erb
<div class="header">
  <%= button_to "Home", root_path, :method => "get" %>

  <h1>All Tags</h1>
</div>

<ul>
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.name, tag_path(tag) %><br>
    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<div class="header">
  <%= button_to "Home", feeds_path, :method => "get" %>

  <h1><%= @tag.name %></h1>
</div>

<ul>
  <% @tag.entries.each do |entry| %>
    <li>
      <%= link_to entry.title, feed_entry_path(entry.feed, entry) %>
      <p><%= "#{entry.author} - #{entry.published_datetime.strftime("%-d %b %Y")} - " %>
        <%=link_to entry.feed.title, feed_path(entry.feed) %></p>
      <p><%= sanitize entry.summary %></p>
    </li><br>
  <% end %>
</ul>