config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :feed_categories
  resources :feeds, only: [:index, :new, :create, :show, :update] do
    member do
      # recognizes get `/feeds/:id/settings` and routes to feeds#settings, w feed.id passed in params[:id] & settings_feed_path helper created
      get 'settings'
      patch 'settings', to: 'feeds#update_settings'
    end
    resources :entries, only: [:show]
    get '/entries', to: 'entries#refresh'
  end
  resources :entries, only: [:index] do
    member do
      get 'settings'
      patch 'settings', to: 'entries#update_settings'
    end
  end
  resources :users
  resources :feed_subscriptions

  get '/feeds/:id/refresh', to: 'feeds#refresh', as: 'refresh_feed'

  #Session Routes
  root 'application#home'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  get '/analytics', to: 'analytics#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?
  before_action :set_current_user

  def set_current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!@current_user
  end

  def home

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.erb
<div class="header">
  <h1>Feedme</h1>

  <h3>Main Menu</h3>
</div>

<ul>
  <li><%= link_to "Feeds", feeds_path %></li>
  <li><%= link_to "Entries", entries_path %></li>
  <li><%= link_to "Feed Categories", feed_categories_path %></li>
  <li><%= link_to "Tags", tags_path %></li>
</ul>

<div class="footer">
  <%= form_tag logout_path do %>
    <%= submit_tag "logout" %>
  <% end %>
</div>